apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: todo
  name: todo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: todo
    spec:
      containers:
      - env:
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              key: MONGO_DB
              name: todo-env
        - name: MONGO_HOST
          value: mongo
        - name: MONGO_PASS
          valueFrom:
               secretKeyRef:
                 name: mongo-secret
                 key: MONGO_PASS
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              key: MONGO_PORT
              name: todo-env
        - name: MONGO_USER
          valueFrom:
               secretKeyRef:
                 name: mongo-secret
                 key: MONGO_USER
        image: pawelfraczyk/node-todo
        name: todo
        ports:
        - containerPort: 8080
        resources: {}
      initContainers:
      - name: init-mongo
        image: busybox
        command: ['sh', '-c', 'until nc -z mongo:27017; do echo waiting for mongo; sleep 2; done;']
      restartPolicy: Always
status: {}